### ISSUE TITLE
large number of warnings when building

### ISSUE THREAD

**Issue by jkandzi** [outboundio/iOS#1]
We're getting a large number of warnings when compiling an Xcode project that uses the outbound library.

Same problem with a possible solution is described here: https://forums.developer.apple.com/thread/17921

> If you have control over those 3rd party libraries (i.e. if you have the source code of their projects) then turn off the setting "Precompile Prefix Header" in the main targets of those libraries.

**Comment by MrTravisB** [comment]
Thanks for bringing this to our attention @jkandzi. Seems this is related to the latest version of Xcode. We'll work on putting in a fix for this. Might not make it in until we ready the next release of the SDK though.

**Comment by nkukushkin** [comment]
Kind of unsettling that this issue has been open for nearly a year.
We're also seeing lots of warnings, have you seen those?

![screen shot 2016-10-04 at 19 19 15](https://cloud.githubusercontent.com/assets/1783104/19082668/ce05aee4-8a67-11e6-9218-12b7c0184986.png)

**Comment by Tang8330** [comment]
We have pushed out a new IOS SDK, that uses Build Settings "DWARF" to mitigate all of these warnings now.

I am going to close this ticket, if the issue still persists on the new version of the SDK, please re-open.

Thanks!
Robin
